import {
  CalendarCheck,
  CalendarDays,
  CalendarPlus,
  ClipboardCheck,
  FileCheck2,
  FolderUp,
  LayoutGrid,
  ListTodo,
  Package,
  Ruler,
  Wrench,
} from "lucide-react";

import type { Recurso } from "../tipos";

/** Catálogo e nichos, e obra e agenda: o que é vendido e como é entregue. */
export const RECURSOS_DE_ENTREGA: readonly Recurso[] = [
  {
    id: "produtos",
    titulo: "Catálogo de produtos",
    resumo: "Custo, margem e preço de venda, com fotos, estoque, fabricante e NCM.",
    detalhes: [
      "O preço de venda sai do custo e da margem, ou é digitado.",
      "O catálogo alimenta a proposta, a nota fiscal e o estoque.",
    ],
    icone: Package,
    requisito: { tipo: "livre" },
    limite: { chave: "maxProducts", unidade: { um: "produto", varios: "produtos", ilimitado: "ilimitados" } },
    rota: "/products",
    ondeFica: "Produtos",
  },
  {
    id: "servicos",
    titulo: "Serviços",
    resumo: "Mão de obra e visitas com valor padrão e os dados da nota de serviço.",
    detalhes: ["Código da LC 116 e alíquota de ISS guardados no próprio serviço."],
    icone: Wrench,
    requisito: { tipo: "livre" },
    rota: "/services",
    ondeFica: "Serviços",
  },
  {
    id: "preco-por-medida",
    titulo: "Preço por medida",
    resumo: "O item é cotado pela medida do vão: por metro quadrado, por faixa de altura ou por metro linear.",
    detalhes: [
      "Largura e altura entram na proposta, e o preço sai da regra do produto.",
      "Cada nicho traz os modos de medida que usa.",
    ],
    icone: Ruler,
    requisito: { tipo: "livre" },
    nichos: "preco-por-medida",
    rota: "/products",
    ondeFica: "Produtos › Preço",
  },
  {
    id: "solucoes",
    titulo: "Pacotes por sistema",
    resumo: "Um sistema montado uma vez, com os produtos padrão, entra inteiro na proposta.",
    detalhes: ["Monte o pacote, reaproveite em cada proposta e ajuste só o que muda."],
    icone: LayoutGrid,
    requisito: { tipo: "livre" },
    nichos: "solutions",
    rota: "/solutions",
    ondeFica: "Soluções",
  },
  {
    id: "ambientes",
    titulo: "Pacotes por local",
    resumo: "Os locais que se repetem, com os produtos que cada um costuma levar.",
    detalhes: ["Escolha o local na proposta e os itens padrão já entram."],
    icone: LayoutGrid,
    requisito: { tipo: "livre" },
    nichos: "ambientes",
    rota: "/ambientes",
    ondeFica: "Ambientes",
  },
  {
    id: "projetos",
    titulo: "Projetos de instalação",
    resumo: "A venda aprovada vira obra, com as etapas do seu segmento já montadas.",
    detalhes: [
      "Checklist e fotos em cada etapa, e o técnico responsável.",
      "A equipe vê as mudanças na hora, sem recarregar.",
      "As etapas padrão mudam por nicho e você edita o modelo.",
    ],
    icone: ClipboardCheck,
    requisito: { tipo: "plano", recursos: ["hasProjects"] },
    rota: "/projects",
    ondeFica: "Obras",
  },
  {
    id: "visita-da-etapa",
    titulo: "Visita marcada pela etapa",
    resumo: "Marcar a visita de uma etapa já põe na agenda e avisa o técnico.",
    detalhes: ["Entra na Agenda da empresa e no Google Agenda de quem vai."],
    icone: CalendarPlus,
    requisito: { tipo: "plano", recursos: ["hasProjects"] },
    rota: "/projects",
    ondeFica: "Obras › Etapa",
  },
  {
    id: "agenda",
    titulo: "Agenda da empresa",
    resumo: "Mês, semana, dia e lista, com arrastar para remarcar.",
    detalhes: [
      "Uma agenda da empresa, com cor e status por compromisso.",
      "Os pedidos de visita chegam para confirmar ou recusar.",
    ],
    icone: CalendarDays,
    requisito: { tipo: "livre" },
    rota: "/calendar",
    ondeFica: "Agenda",
  },
  {
    id: "google-agenda",
    titulo: "Google Agenda",
    resumo: "A agenda do ERP sincronizada com o Google Agenda de cada pessoa.",
    detalhes: ["Visitas e compromissos aparecem no celular de quem vai."],
    icone: CalendarCheck,
    requisito: { tipo: "plano", recursos: ["hasCalendarSync"] },
    rota: "/calendar",
    ondeFica: "Agenda › Google",
  },
  {
    id: "tarefas",
    titulo: "Tarefas com menção",
    resumo: "O que fazer, de quem e até quando, com @menção que avisa a pessoa.",
    detalhes: [
      "Aparecem no contato, na proposta, no lead e no painel do dia.",
      "Lembrete no dia do prazo.",
    ],
    icone: ListTodo,
    requisito: { tipo: "livre" },
    rota: "/tasks",
    ondeFica: "Tarefas",
  },
  {
    id: "google-drive",
    titulo: "Proposta no Google Drive",
    resumo: "O PDF da proposta cai sozinho na pasta do cliente, no Drive da empresa.",
    detalhes: ["A pasta é criada pela ProOps; nada é lido do seu Drive."],
    icone: FolderUp,
    requisito: { tipo: "plano", recursos: ["hasDriveSync"] },
    rota: "/settings/drive",
    ondeFica: "Configurações › Google Drive",
  },
  {
    id: "aceite-da-entrega",
    titulo: "Aceite da entrega",
    resumo: "O cliente confere a obra pelo link e aceita a entrega com nome e documento.",
    detalhes: ["A obra fecha e a equipe é avisada no aceite."],
    icone: FileCheck2,
    requisito: { tipo: "plano", recursos: ["hasProjects"] },
    rota: "/projects",
    ondeFica: "Obras › Link da entrega",
  },
];
