import {
  ArrowLeftRight,
  BadgePercent,
  BarChart3,
  Bot,
  FileInput,
  FileText,
  Gauge,
  GraduationCap,
  KeyRound,
  Lock,
  MessageCircle,
  Receipt,
  Smartphone,
  Sparkles,
  Table2,
  TrendingUp,
  UserCog,
  Wallet,
  Bell,
} from "lucide-react";

import { FISCAL_ADDON_MONTHLY_INVOICES } from "@/lib/plans/addon-definitions";

import type { Recurso } from "../tipos";

/** Financeiro, fiscal, Lia e a plataforma em volta. */
export const RECURSOS_DE_GESTAO: readonly Recurso[] = [
  {
    id: "lancamentos",
    categoria: "financeiro",
    titulo: "Lançamentos da venda",
    resumo: "A proposta aprovada já cria a entrada e as parcelas, e você só dá baixa.",
    detalhes: [
      "Avulsos, parcelados e recorrentes, com custos extras e categorias.",
      "As parcelas de uma venda aparecem juntas na aba Agrupados.",
      "Baixa em lote, exportação para Excel e exclusão com desfazer.",
    ],
    icone: ArrowLeftRight,
    requisito: { tipo: "plano", recursos: ["hasFinancial"] },
    rota: "/transactions",
    ondeFica: "Financeiro › Lançamentos",
  },
  {
    id: "carteiras",
    categoria: "financeiro",
    titulo: "Carteiras",
    resumo: "Contas, caixa e cartões com saldo que se atualiza a cada baixa.",
    detalhes: ["Transferência entre carteiras, ajuste de saldo e histórico."],
    icone: Wallet,
    requisito: { tipo: "plano", recursos: ["hasFinancial"] },
    rota: "/wallets",
    ondeFica: "Financeiro › Carteiras",
  },
  {
    id: "comissoes",
    categoria: "financeiro",
    titulo: "Comissões de vendedor e arquiteto",
    resumo: "Quanto cada parceiro recebe no mês, no mesmo ritmo em que o cliente paga.",
    detalhes: [
      "Cliente parcelou, a comissão acompanha as mesmas datas.",
      "O percentual mora na ficha do vendedor ou do arquiteto.",
    ],
    icone: BadgePercent,
    requisito: { tipo: "plano", recursos: ["hasFinancial"] },
    rota: "/commissions",
    ondeFica: "Financeiro › Comissões",
  },
  {
    id: "dre",
    categoria: "financeiro",
    titulo: "DRE",
    resumo: "Receita, impostos, custos e despesas do período, por caixa ou competência.",
    detalhes: ["Cada categoria ligada a uma linha do DRE.", "Até 12 meses lado a lado."],
    icone: BarChart3,
    requisito: { tipo: "plano", recursos: ["hasFinancial"] },
    rota: "/dre",
    ondeFica: "Financeiro › DRE",
  },
  {
    id: "fluxo-de-caixa",
    categoria: "financeiro",
    titulo: "Fluxo de caixa em três cenários",
    resumo: "O saldo dos próximos meses se o cliente pagar tudo, parte ou com atraso.",
    detalhes: [
      "Parte do saldo das carteiras, soma o que entra e desconta o que sai.",
      "Pessimista, realista e otimista, com o percentual recebido e os dias de atraso ajustáveis.",
    ],
    icone: TrendingUp,
    requisito: { tipo: "plano", recursos: ["hasFinancial"] },
    rota: "/cash-flow",
    ondeFica: "Financeiro › Fluxo de caixa",
  },
  {
    id: "painel",
    categoria: "financeiro",
    titulo: "Painel do dia",
    resumo: "O que vence, o que precisa de atenção e o resultado do mês numa tela.",
    detalhes: [
      "Vendido, em negociação, conversão e ticket médio do mês.",
      "Aceites a confirmar, pedidos de mudança e propostas paradas em destaque.",
      "Os gráficos de caixa aparecem com o financeiro no plano.",
    ],
    icone: Gauge,
    requisito: { tipo: "livre" },
    rota: "/dashboard",
    ondeFica: "Painel",
  },
  {
    id: "notas-fiscais",
    categoria: "fiscal",
    titulo: "NF-e e NFS-e",
    resumo: "A nota sai da proposta aprovada ou do lançamento, sem digitar de novo.",
    detalhes: [
      "Nota de produto e de serviço, no padrão nacional e no municipal.",
      "PDF e XML guardados, carta de correção e cancelamento.",
      `No add-on, até ${FISCAL_ADDON_MONTHLY_INVOICES} notas por mês.`,
    ],
    icone: Receipt,
    requisito: { tipo: "plano", recursos: ["hasFiscal"] },
    rota: "/invoices",
    ondeFica: "Notas fiscais",
  },
  {
    id: "certificado",
    categoria: "fiscal",
    titulo: "Certificado A1 sob controle",
    resumo: "Aviso antes de o certificado vencer, para a emissão não parar no dia.",
    detalhes: ["Avisos com 30, 15, 7 e 1 dia de antecedência.", "Configuração guiada em quatro passos."],
    icone: KeyRound,
    requisito: { tipo: "plano", recursos: ["hasFiscal"] },
    rota: "/settings/fiscal",
    ondeFica: "Configurações › Fiscal",
  },
  {
    id: "notas-de-entrada",
    categoria: "fiscal",
    titulo: "Notas de entrada",
    resumo: "As notas que os fornecedores emitem para o seu CNPJ chegam sozinhas.",
    detalhes: ["Busca de hora em hora.", "Cada nota recebida vira despesa com um clique."],
    icone: FileInput,
    requisito: { tipo: "plano", recursos: ["hasFiscalReceiving"] },
    rota: "/invoices",
    ondeFica: "Notas fiscais › Recebidas",
  },
  {
    id: "lia-acoes",
    categoria: "lia",
    titulo: "Lia, a IA que executa",
    resumo: "Peça em português e a Lia faz: cria a proposta, lança, dá baixa, move o lead.",
    detalhes: [
      "Propostas, contatos, produtos, lançamentos, carteiras e leads.",
      "Antes de mudar qualquer coisa, ela mostra o que vai fazer e espera a sua confirmação.",
      "Respeita as permissões de quem pede: o que a pessoa não pode, a Lia também não faz.",
    ],
    icone: Bot,
    requisito: { tipo: "plano", limites: ["aiMessagesPerMonth"] },
    limite: {
      chave: "aiMessagesPerMonth",
      unidade: { um: "mensagem", varios: "mensagens", ilimitado: "sem limite", sufixo: "por mês" },
    },
  },
  {
    id: "lia-textos",
    categoria: "lia",
    titulo: "Textos escritos pela IA",
    resumo: "Descrição de produto, observações da proposta e seções do PDF, escritas num clique.",
    detalhes: ["Você revisa e ajusta antes de salvar.", "A Lia também sugere o NCM do produto para a nota fiscal."],
    icone: Sparkles,
    requisito: { tipo: "tier", minimo: "pro" },
  },
  {
    id: "equipe",
    categoria: "plataforma",
    titulo: "Equipe e permissões",
    resumo: "Ver, criar, editar e excluir definidos por tela para cada pessoa.",
    detalhes: ["Perfis prontos para começar e ajuste fino depois.", "A mudança vale na hora, sem novo login."],
    icone: UserCog,
    requisito: { tipo: "livre" },
    limite: { chave: "maxUsers", unidade: { um: "usuário", varios: "usuários", ilimitado: "ilimitados" } },
    rota: "/settings/team",
    ondeFica: "Configurações › Equipe",
  },
  {
    id: "duas-etapas",
    categoria: "plataforma",
    titulo: "Login em duas etapas",
    resumo: "Aplicativo autenticador ou código no WhatsApp, com códigos de recuperação.",
    detalhes: ["Os dois métodos podem conviver na mesma conta."],
    icone: Lock,
    requisito: { tipo: "livre" },
    rota: "/settings/security",
    ondeFica: "Configurações › Segurança",
  },
  {
    id: "notificacoes",
    categoria: "plataforma",
    titulo: "Central de notificações",
    resumo: "Cada pessoa escolhe o que recebe no sino e o que chega por e-mail.",
    detalhes: ["Histórico próprio, com o que já foi lido."],
    icone: Bell,
    requisito: { tipo: "livre" },
    rota: "/notifications",
    ondeFica: "Notificações",
  },
  {
    id: "whatsapp",
    categoria: "plataforma",
    titulo: "Consultas pelo WhatsApp",
    resumo: "Propostas com PDF, resumo do dia e da semana, saldo e lançamentos, numa conversa.",
    detalhes: ["Um menu de consultas rápidas, sem abrir o computador.", "Envia o link de um lançamento para o cliente."],
    icone: MessageCircle,
    requisito: { tipo: "plano", recursos: ["hasWhatsApp"] },
    ondeFica: "WhatsApp",
  },
  {
    id: "planilhas",
    categoria: "plataforma",
    titulo: "Planilhas internas",
    resumo: "Planilhas com fórmulas dentro do ERP, para o que foge do fluxo padrão.",
    detalhes: ["Importa e exporta Excel e CSV."],
    icone: Table2,
    requisito: { tipo: "livre" },
    limite: { chave: "maxSpreadsheets", unidade: { um: "planilha", varios: "planilhas", ilimitado: "ilimitadas" } },
    rota: "/spreadsheets",
    ondeFica: "Planilhas",
  },
  {
    id: "celular",
    categoria: "plataforma",
    titulo: "No celular",
    resumo: "O ERP inteiro adaptado à tela pequena, com barra de navegação embaixo.",
    detalhes: ["Instalável na tela inicial, como um aplicativo."],
    icone: Smartphone,
    requisito: { tipo: "livre" },
  },
  {
    id: "tutorial",
    categoria: "plataforma",
    titulo: "Tutorial guiado",
    resumo: "Um roteiro tela a tela para a equipe começar sem treinamento.",
    detalhes: ["Um painel de ajuda em cada tela, com o que ela faz."],
    icone: GraduationCap,
    requisito: { tipo: "livre" },
  },
  {
    id: "documentos",
    categoria: "plataforma",
    titulo: "Arquivos da empresa",
    resumo: "Anexos de propostas, fotos de obra e PDFs guardados junto do que eles contam.",
    detalhes: ["Espaço de armazenamento de acordo com o plano."],
    icone: FileText,
    requisito: { tipo: "livre" },
  },
];
