import {
  BellRing,
  Contact,
  FileSpreadsheet,
  FileText,
  Hash,
  KanbanSquare,
  MessageSquareDiff,
  Palette,
  PenLine,
  Search,
  Send,
  Target,
  UserSearch,
} from "lucide-react";

import type { Recurso } from "../tipos";

/** CRM e clientes, e propostas e vendas: do contato ao "aceito". */
export const RECURSOS_DE_VENDA: readonly Recurso[] = [
  {
    id: "leads",
    titulo: "Leads com próxima ação",
    resumo: "Cada contato novo entra no funil com origem, valor estimado e o próximo passo marcado.",
    detalhes: [
      "Etapas Novo, Em contato, Qualificado, Convertido e Perdido.",
      "Ligação, visita e reunião ficam na linha do tempo do lead.",
      "Converter o lead cria o cliente e abre uma proposta para ele.",
    ],
    icone: UserSearch,
    requisito: { tipo: "plano", recursos: ["hasKanban"] },
    rota: "/crm",
    ondeFica: "CRM › Leads",
  },
  {
    id: "funil-de-propostas",
    titulo: "Funil de propostas",
    resumo: "As propostas num quadro com as suas colunas, arrastadas de etapa em etapa.",
    detalhes: [
      "Colunas com os nomes que a sua equipe usa.",
      "Arrastar o cartão muda o status da proposta.",
      "Um quadro próprio para os lançamentos pendentes, atrasados e pagos.",
    ],
    icone: KanbanSquare,
    requisito: { tipo: "plano", recursos: ["hasKanban"] },
    rota: "/crm",
    ondeFica: "CRM",
  },
  {
    id: "contatos",
    titulo: "Clientes, fornecedores e parceiros",
    resumo: "Uma ficha por contato com propostas, financeiro, notas e anotações no mesmo lugar.",
    detalhes: [
      "Cliente, fornecedor, vendedor e arquiteto na mesma lista.",
      "Vendedor e arquiteto levam o percentual de comissão na própria ficha.",
      "Próximas ações da equipe aparecem na ficha de quem elas envolvem.",
    ],
    icone: Contact,
    requisito: { tipo: "livre" },
    limite: { chave: "maxClients", unidade: { um: "cliente", varios: "clientes", ilimitado: "ilimitados" } },
    rota: "/contacts",
    ondeFica: "Contatos",
  },
  {
    id: "importacao",
    titulo: "Importação por planilha",
    resumo: "Contatos, produtos e serviços que já estão no Excel entram em minutos.",
    detalhes: [
      "Aceita .xlsx e .csv, com modelo para baixar.",
      "As colunas são ligadas sozinhas pelo nome.",
      "Prévia antes de gravar, com os repetidos apontados.",
    ],
    icone: FileSpreadsheet,
    requisito: { tipo: "livre" },
    rota: "/contacts",
    ondeFica: "Contatos, Produtos e Serviços › Importar",
  },
  {
    id: "busca-global",
    titulo: "Busca em qualquer tela",
    resumo: "Um atalho acha proposta, contato ou tela sem sair de onde você está.",
    detalhes: ["Guarda os abertos recentemente.", "Funciona com o teclado do começo ao fim."],
    icone: Search,
    requisito: { tipo: "livre" },
  },
  {
    id: "propostas",
    titulo: "Proposta em passos",
    resumo: "Cliente, itens, pagamento e PDF num assistente que salva o rascunho sozinho.",
    detalhes: [
      "Itens agrupados por local e por sistema, com subtotal por grupo.",
      "Entrada e parcelas definidas na própria proposta.",
      "Anexos, campos personalizados e duplicar a partir de uma proposta antiga.",
      "Excluiu sem querer? Dá para desfazer.",
    ],
    icone: FileText,
    requisito: { tipo: "livre" },
    limite: {
      chave: "maxProposals",
      unidade: { um: "proposta", varios: "propostas", ilimitado: "ilimitadas", sufixo: "por mês" },
    },
    rota: "/proposals",
    ondeFica: "Propostas",
  },
  {
    id: "aceite-online",
    titulo: "Aceite online",
    resumo: "O cliente aceita a proposta pelo link com nome e CPF ou CNPJ, e você confirma.",
    detalhes: [
      "O aceite fica registrado com data e documento de quem aceitou.",
      "Confirmado o aceite, nascem os lançamentos, as comissões e a obra.",
    ],
    icone: PenLine,
    requisito: { tipo: "plano", recursos: ["hasOnlineApproval"] },
    rota: "/proposals",
    ondeFica: "Propostas › Link do cliente",
  },
  {
    id: "pedido-de-mudancas",
    titulo: "Pedido de mudanças",
    resumo: "Em vez de recusar, o cliente pede ajustes pelo link, com o motivo escrito.",
    detalhes: [
      "Os pedidos ficam em ordem no link e na proposta.",
      "Você ajusta, reenvia o mesmo link e o cliente vê a versão nova.",
    ],
    icone: MessageSquareDiff,
    requisito: { tipo: "plano", recursos: ["hasOnlineApproval"] },
    rota: "/proposals",
    ondeFica: "Propostas › Link do cliente",
  },
  {
    id: "alertas-de-proposta",
    titulo: "Aviso quando o cliente abre",
    resumo: "Você sabe quando a proposta foi aberta e quem está esperando resposta há dias.",
    detalhes: [
      "Aviso na hora em que o cliente abre o link.",
      "Lembrete quando ele viu e não respondeu em três dias.",
      "Aviso diário das propostas perto de vencer.",
    ],
    icone: BellRing,
    requisito: { tipo: "livre" },
    ondeFica: "Notificações",
  },
  {
    id: "envio-da-proposta",
    titulo: "Envio pelo WhatsApp e e-mail da empresa",
    resumo: "O botão abre o seu WhatsApp ou e-mail com a mensagem e o link prontos.",
    detalhes: [
      "Sai do número e do e-mail da sua empresa, não de um remetente genérico.",
      "Vale para proposta, cobrança, portal, obra e link do contador.",
    ],
    icone: Send,
    requisito: { tipo: "livre" },
    rota: "/proposals",
    ondeFica: "Propostas › Enviar",
  },
  {
    id: "editor-de-pdf",
    titulo: "Editor de PDF",
    resumo: "Capa, seções, fontes e cores da proposta, com a prévia ao lado.",
    detalhes: [
      "Temas prontos para partir de um desenho que já funciona.",
      "Você escolhe o que aparece: fotos, preços, medidas, subtotais por grupo.",
      "Modelos de texto reaproveitados de proposta em proposta.",
    ],
    icone: FileText,
    requisito: { tipo: "plano", recursos: ["canEditPdfSections"] },
    rota: "/proposals",
    ondeFica: "Propostas › Editar PDF",
  },
  {
    id: "cores-da-marca",
    titulo: "Cores da sua marca",
    resumo: "A cor da empresa aplicada no sistema e na proposta que o cliente recebe.",
    detalhes: ["Escolha a cor principal e ela passa a vestir a proposta."],
    icone: Palette,
    requisito: { tipo: "plano", recursos: ["canCustomizeTheme"] },
    rota: "/profile",
    ondeFica: "Perfil da empresa",
  },
  {
    id: "numeracao",
    titulo: "Numeração de propostas",
    resumo: "Código sequencial por empresa, que também dá nome ao arquivo do PDF.",
    detalhes: [
      "Sequência, ano e praça no mesmo código.",
      "Continua a numeração que você já usava.",
      "Validade padrão das propostas definida no mesmo lugar.",
    ],
    icone: Hash,
    requisito: { tipo: "livre" },
    rota: "/settings/proposals",
    ondeFica: "Configurações › Propostas",
  },
  {
    id: "metas",
    titulo: "Metas de vendas",
    resumo: "Meta do mês da empresa e de cada vendedor, acompanhada no painel.",
    detalhes: [
      "O progresso é o valor das propostas aprovadas no mês.",
      "Cada proposta leva o responsável pela venda.",
    ],
    icone: Target,
    requisito: { tipo: "plano", recursos: ["hasSalesGoals"] },
    rota: "/settings/goals",
    ondeFica: "Configurações › Metas",
  },
];
